name: Frontend CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Notify Render for Deployment
      run: curl -X POST https://api.render.com/webhooks/WEB_HOOK_FE
